name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo test --verbose --no-run --features clap_mangen,clap_complete
    - name: Run tests
      run: cargo test --verbose

  static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl
    - name: Install host deps
      run: sudo apt-get install -y musl-tools
    - name: Build + link statically
      run: cargo build --verbose --release --target=x86_64-unknown-linux-musl --features vendored-openssl
    - name: Validate binary is statically linked
      run: ldd ./target/x86_64-unknown-linux-musl/release/prr 2>&1 | grep -q "statically linked"

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run rustfmt
      run: cargo fmt --check
